version: "3.3"
services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    environment:
      EULA: "TRUE"
    ports:
      - "25565:25565"
    restart: always
    tty: TRUE
    stdin_open: TRUE
    volumes:
      - type: bind
        source: ./data
        target: /data
